spring:
  datasource:
    url: dbhost.students.cs.ubc.ca
    username: #username
    password: #password
    driver-class-name: oracle.jdbc.OracleDriver


#spring.datasource.url=jdbc:oracle:thin:@//localhost:11521/ORCLPDB1
#spring.datasource.username=books
#spring.datasource.password=books
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
