spring:
  application:
    name: real-estate-project
  datasource:
    url: jdbc:oracle:thin:@localhost:3336:stu
    username: #username
    password: #password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    url: jdbc:oracle:thin:@localhost:3336:stu
    user: #username
    password: #password
    schemas: #schema
    locations: classpath:db/migration/oracle

server:
  port: 8080
